### ISSUE TITLE
Split of console functionality

### ISSUE THREAD

**Issue by elektro-potkan** [contributte/scheduler#24]
Hello all,

I would like to ask You , if You would mind separating the console functionality into its own package?
E.g. into a couple of `scheduler` & `scheduler-console` or `scheduler-base` & `scheduler` packages?

As I mostly do not use the console functionality at all
(I am calling the scheduler's run method from presenter),
all those console-related dependencies is completely unnecessary for me.

Thank You for Your reply.

Best regards

**Comment by f3l1x** [comment]
Hi @elektro-potkan. I'm ok with current setup.
